import type { Brand, Category, Lead, Product } from "./types";

export const seedCategories: Category[] = [
  {
    id: "cat-may-xit-rua",
    name: "Máy Xịt Rửa Áp Lực",
    slug: "may-xit-rua-ap-luc",
    parentId: null,
    sortOrder: 1,
  },
  {
    id: "cat-gia-dinh",
    name: "Máy xịt rửa gia đình",
    slug: "may-xit-rua-gia-dinh",
    parentId: "cat-may-xit-rua",
    sortOrder: 1,
  },
  {
    id: "cat-cong-nghiep",
    name: "Máy xịt rửa công nghiệp",
    slug: "may-xit-rua-cong-nghiep",
    parentId: "cat-may-xit-rua",
    sortOrder: 2,
  },
  {
    id: "cat-phu-kien",
    name: "Phụ kiện máy xịt rửa",
    slug: "phu-kien-may-xit-rua",
    parentId: "cat-may-xit-rua",
    sortOrder: 3,
  },
];

export const seedBrands: Brand[] = [
  { id: "brand-dekton", name: "Dekton", slug: "dekton" },
  { id: "brand-bosch", name: "Bosch", slug: "bosch" },
  { id: "brand-karcher", name: "Kärcher", slug: "karcher" },
];

function mediaImg(
  productId: string,
  index: number,
  alt: string,
): Product["media"][number] {
  return {
    id: `${productId}-media-${index}`,
    productId,
    kind: "image",
    url: `https://picsum.photos/seed/${productId}-${index}/800/800`,
    alt,
    sortOrder: index,
    storagePath: null,
    posterUrl: null,
  };
}

export const seedProducts: Product[] = [
  {
    id: "prod-dekton-dk-1400",
    name: "Máy xịt rửa áp lực Dekton DK-1400",
    slug: "may-xit-rua-dekton-dk-1400",
    model: "DK-1400",
    brandId: "brand-dekton",
    categoryId: "cat-gia-dinh",
    price: 1_890_000,
    salePrice: 1_490_000,
    stockStatus: "in_stock",
    soldCount: 1286,
    warranty: "12 tháng",
    origin: "Trung Quốc",
    motor: "Induction 1400W",
    specs: {
      "Công suất": "1400W",
      "Áp lực": "100 bar",
      "Lưu lượng": "6.5 L/phút",
      "Điện áp": "220V-50Hz",
      "Trọng lượng": "5.2 kg",
    },
    isPublished: true,
    description:
      "Máy xịt rửa áp lực Dekton DK-1400 phù hợp vệ sinh xe máy, sân nhà, ban công. Motor cảm ứng bền, vận hành êm.",
    media: [
      mediaImg("prod-dekton-dk-1400", 0, "Dekton DK-1400 mặt trước"),
      mediaImg("prod-dekton-dk-1400", 1, "Dekton DK-1400 phụ kiện"),
    ],
  },
  {
    id: "prod-dekton-dk-1800",
    name: "Máy xịt rửa áp lực Dekton DK-1800",
    slug: "may-xit-rua-dekton-dk-1800",
    model: "DK-1800",
    brandId: "brand-dekton",
    categoryId: "cat-gia-dinh",
    price: 2_490_000,
    salePrice: 1_990_000,
    stockStatus: "in_stock",
    soldCount: 942,
    warranty: "12 tháng",
    origin: "Trung Quốc",
    motor: "Induction 1800W",
    specs: {
      "Công suất": "1800W",
      "Áp lực": "120 bar",
      "Lưu lượng": "7.2 L/phút",
      "Điện áp": "220V-50Hz",
      "Trọng lượng": "6.8 kg",
    },
    isPublished: true,
    description:
      "Dekton DK-1800 công suất cao hơn, rửa xe ô tô và sân vườn hiệu quả, kèm đầu phun đa chế độ.",
    media: [
      mediaImg("prod-dekton-dk-1800", 0, "Dekton DK-1800"),
      mediaImg("prod-dekton-dk-1800", 1, "Dekton DK-1800 đang sử dụng"),
    ],
  },
  {
    id: "prod-dekton-dk-2200",
    name: "Máy xịt rửa áp lực Dekton DK-2200",
    slug: "may-xit-rua-dekton-dk-2200",
    model: "DK-2200",
    brandId: "brand-dekton",
    categoryId: "cat-gia-dinh",
    price: 3_290_000,
    salePrice: 2_690_000,
    stockStatus: "in_stock",
    soldCount: 715,
    warranty: "18 tháng",
    origin: "Trung Quốc",
    motor: "Induction 2200W",
    specs: {
      "Công suất": "2200W",
      "Áp lực": "140 bar",
      "Lưu lượng": "8.0 L/phút",
      "Dây cao áp": "8 m",
      "Trọng lượng": "8.5 kg",
    },
    isPublished: true,
    description:
      "DK-2200 dòng gia đình cao cấp, áp lực mạnh, dây dài tiện di chuyển quanh nhà.",
    media: [mediaImg("prod-dekton-dk-2200", 0, "Dekton DK-2200")],
  },
  {
    id: "prod-dekton-dk-3000",
    name: "Máy xịt rửa áp lực Dekton DK-3000 Pro",
    slug: "may-xit-rua-dekton-dk-3000-pro",
    model: "DK-3000",
    brandId: "brand-dekton",
    categoryId: "cat-cong-nghiep",
    price: 5_490_000,
    salePrice: 4_790_000,
    stockStatus: "in_stock",
    soldCount: 318,
    warranty: "24 tháng",
    origin: "Trung Quốc",
    motor: "Induction 3000W",
    specs: {
      "Công suất": "3000W",
      "Áp lực": "180 bar",
      "Lưu lượng": "10 L/phút",
      "Dây cao áp": "10 m",
      "Trọng lượng": "14 kg",
    },
    isPublished: true,
    description:
      "Dekton DK-3000 Pro dành cho gara, quán rửa xe nhỏ — áp lực cao, motor công nghiệp.",
    media: [
      mediaImg("prod-dekton-dk-3000", 0, "Dekton DK-3000 Pro"),
      mediaImg("prod-dekton-dk-3000", 1, "Dekton DK-3000 chi tiết"),
    ],
  },
  {
    id: "prod-dekton-dk-3500",
    name: "Máy xịt rửa áp lực Dekton DK-3500",
    slug: "may-xit-rua-dekton-dk-3500",
    model: "DK-3500",
    brandId: "brand-dekton",
    categoryId: "cat-cong-nghiep",
    price: 7_890_000,
    salePrice: 6_990_000,
    stockStatus: "in_stock",
    soldCount: 156,
    warranty: "24 tháng",
    origin: "Trung Quốc",
    motor: "Induction 3500W",
    specs: {
      "Công suất": "3500W",
      "Áp lực": "200 bar",
      "Lưu lượng": "12 L/phút",
      "Dây cao áp": "15 m",
      "Trọng lượng": "22 kg",
    },
    isPublished: true,
    description:
      "DK-3500 công suất lớn cho tiệm rửa xe, vệ sinh nhà xưởng nhẹ.",
    media: [mediaImg("prod-dekton-dk-3500", 0, "Dekton DK-3500")],
  },
  {
    id: "prod-dekton-dk-mini",
    name: "Máy xịt rửa cầm tay Dekton Mini DK-M20",
    slug: "may-xit-rua-dekton-mini-dk-m20",
    model: "DK-M20",
    brandId: "brand-dekton",
    categoryId: "cat-gia-dinh",
    price: 890_000,
    salePrice: 690_000,
    stockStatus: "in_stock",
    soldCount: 2104,
    warranty: "6 tháng",
    origin: "Trung Quốc",
    motor: "Brushless 20V",
    specs: {
      "Pin": "20V 2.0Ah",
      "Áp lực": "25 bar",
      "Dung tích bình": "0.5 L",
      "Trọng lượng": "1.1 kg",
    },
    isPublished: true,
    description:
      "Máy xịt cầm tay pin sạc Dekton Mini — rửa xe máy, kính, ban công không cần ổ điện.",
    media: [mediaImg("prod-dekton-dk-mini", 0, "Dekton Mini DK-M20")],
  },
  {
    id: "prod-bosch-aquatak-110",
    name: "Máy xịt rửa Bosch EasyAquatak 110",
    slug: "may-xit-rua-bosch-easyaquatak-110",
    model: "EasyAquatak 110",
    brandId: "brand-bosch",
    categoryId: "cat-gia-dinh",
    price: 3_150_000,
    salePrice: 2_790_000,
    stockStatus: "in_stock",
    soldCount: 534,
    warranty: "12 tháng",
    origin: "Đức / lắp ráp Trung Quốc",
    motor: "1300W",
    specs: {
      "Công suất": "1300W",
      "Áp lực": "110 bar",
      "Lưu lượng": "330 L/giờ",
      "Dây cao áp": "5 m",
      "Trọng lượng": "4.6 kg",
    },
    isPublished: true,
    description:
      "Bosch EasyAquatak 110 gọn nhẹ, thương hiệu Đức tin cậy cho hộ gia đình.",
    media: [
      mediaImg("prod-bosch-aquatak-110", 0, "Bosch EasyAquatak 110"),
      mediaImg("prod-bosch-aquatak-110", 1, "Bosch EasyAquatak 110 hộp"),
    ],
  },
  {
    id: "prod-bosch-aquatak-150",
    name: "Máy xịt rửa Bosch UniversalAquatak 150",
    slug: "may-xit-rua-bosch-universalaquatak-150",
    model: "UniversalAquatak 150",
    brandId: "brand-bosch",
    categoryId: "cat-gia-dinh",
    price: 5_990_000,
    salePrice: 5_290_000,
    stockStatus: "in_stock",
    soldCount: 289,
    warranty: "24 tháng",
    origin: "Đức / lắp ráp Trung Quốc",
    motor: "2100W",
    specs: {
      "Công suất": "2100W",
      "Áp lực": "150 bar",
      "Lưu lượng": "480 L/giờ",
      "Dây cao áp": "8 m",
      "Trọng lượng": "9.3 kg",
    },
    isPublished: true,
    description:
      "UniversalAquatak 150 áp lực mạnh, phù hợp rửa xe SUV và sân rộng.",
    media: [mediaImg("prod-bosch-aquatak-150", 0, "Bosch UniversalAquatak 150")],
  },
  {
    id: "prod-karcher-k2",
    name: "Máy xịt rửa Kärcher K2 Compact",
    slug: "may-xit-rua-karcher-k2-compact",
    model: "K2 Compact",
    brandId: "brand-karcher",
    categoryId: "cat-gia-dinh",
    price: 2_890_000,
    salePrice: 2_450_000,
    stockStatus: "in_stock",
    soldCount: 876,
    warranty: "12 tháng",
    origin: "Đức",
    motor: "1400W",
    specs: {
      "Công suất": "1400W",
      "Áp lực": "110 bar",
      "Lưu lượng": "360 L/giờ",
      "Dây cao áp": "4 m",
      "Trọng lượng": "4.0 kg",
    },
    isPublished: true,
    description:
      "Kärcher K2 Compact siêu gọn, lý tưởng căn hộ / nhà phố nhỏ.",
    media: [
      mediaImg("prod-karcher-k2", 0, "Kärcher K2 Compact"),
      mediaImg("prod-karcher-k2", 1, "Kärcher K2 đang xịt"),
    ],
  },
  {
    id: "prod-karcher-k5",
    name: "Máy xịt rửa Kärcher K5 Premium",
    slug: "may-xit-rua-karcher-k5-premium",
    model: "K5 Premium",
    brandId: "brand-karcher",
    categoryId: "cat-cong-nghiep",
    price: 12_990_000,
    salePrice: 11_490_000,
    stockStatus: "in_stock",
    soldCount: 97,
    warranty: "24 tháng",
    origin: "Đức",
    motor: "2100W",
    specs: {
      "Công suất": "2100W",
      "Áp lực": "145 bar",
      "Lưu lượng": "500 L/giờ",
      "Dây cao áp": "10 m",
      "Trọng lượng": "13.6 kg",
    },
    isPublished: true,
    description:
      "Kärcher K5 Premium dòng cao cấp, điều chỉnh áp lực thông minh, bền bỉ.",
    media: [mediaImg("prod-karcher-k5", 0, "Kärcher K5 Premium")],
  },
  {
    id: "prod-dekton-dk-2500",
    name: "Máy xịt rửa áp lực Dekton DK-2500",
    slug: "may-xit-rua-dekton-dk-2500",
    model: "DK-2500",
    brandId: "brand-dekton",
    categoryId: "cat-cong-nghiep",
    price: 4_290_000,
    salePrice: null,
    stockStatus: "out_of_stock",
    soldCount: 421,
    warranty: "18 tháng",
    origin: "Trung Quốc",
    motor: "Induction 2500W",
    specs: {
      "Công suất": "2500W",
      "Áp lực": "160 bar",
      "Lưu lượng": "9 L/phút",
      "Dây cao áp": "10 m",
    },
    isPublished: true,
    description: "DK-2500 tạm hết hàng — đặt trước để nhận khi về kho.",
    media: [mediaImg("prod-dekton-dk-2500", 0, "Dekton DK-2500")],
  },
  {
    id: "prod-dekton-dk-legacy",
    name: "Máy xịt rửa Dekton DK-1000 (ngừng SX)",
    slug: "may-xit-rua-dekton-dk-1000",
    model: "DK-1000",
    brandId: "brand-dekton",
    categoryId: "cat-gia-dinh",
    price: 1_290_000,
    salePrice: null,
    stockStatus: "discontinued",
    soldCount: 3200,
    warranty: "Hết bảo hành hãng",
    origin: "Trung Quốc",
    motor: "1000W",
    specs: {
      "Công suất": "1000W",
      "Áp lực": "80 bar",
      "Lưu lượng": "5.5 L/phút",
    },
    isPublished: false,
    description: "Model cũ đã ngừng sản xuất — chỉ hiển thị nội bộ admin.",
    media: [mediaImg("prod-dekton-dk-legacy", 0, "Dekton DK-1000")],
  },
  {
    id: "prod-acc-sung-phun",
    name: "Súng phun áp lực Dekton chuẩn nhanh",
    slug: "sung-phun-ap-luc-dekton",
    model: "ACC-GUN-01",
    brandId: "brand-dekton",
    categoryId: "cat-phu-kien",
    price: 320_000,
    salePrice: 259_000,
    stockStatus: "in_stock",
    soldCount: 1840,
    warranty: "3 tháng",
    origin: "Trung Quốc",
    motor: null,
    specs: {
      "Chuẩn khớp": "Quick connect",
      "Chất liệu": "Nhựa ABS + đồng",
      "Áp lực tối đa": "200 bar",
    },
    isPublished: true,
    description: "Súng phun thay thế / nâng cấp cho máy xịt Dekton và tương thích.",
    media: [mediaImg("prod-acc-sung-phun", 0, "Súng phun Dekton")],
  },
  {
    id: "prod-acc-day-cao-ap",
    name: "Dây cao áp 10m chuẩn Kärcher / Dekton",
    slug: "day-cao-ap-10m",
    model: "ACC-HOSE-10",
    brandId: "brand-dekton",
    categoryId: "cat-phu-kien",
    price: 450_000,
    salePrice: 379_000,
    stockStatus: "in_stock",
    soldCount: 1120,
    warranty: "6 tháng",
    origin: "Trung Quốc",
    motor: null,
    specs: {
      "Chiều dài": "10 m",
      "Áp lực tối đa": "250 bar",
      "Đầu nối": "M22 / Quick",
    },
    isPublished: true,
    description: "Dây cao áp gia cố, chống xoắn, dùng cho máy gia đình và bán công nghiệp.",
    media: [mediaImg("prod-acc-day-cao-ap", 0, "Dây cao áp 10m")],
  },
  {
    id: "prod-acc-voi-xoay",
    name: "Đầu phun xoay 360° Bosch / đa năng",
    slug: "dau-phun-xoay-360",
    model: "ACC-NOZZLE-360",
    brandId: "brand-bosch",
    categoryId: "cat-phu-kien",
    price: 280_000,
    salePrice: 199_000,
    stockStatus: "in_stock",
    soldCount: 965,
    warranty: "3 tháng",
    origin: "Trung Quốc",
    motor: null,
    specs: {
      "Góc xoay": "360°",
      "Chất liệu": "Đồng + thép không gỉ",
      "Tương thích": "Bosch, Dekton, Kärcher (adapter)",
    },
    isPublished: true,
    description: "Đầu phun xoay làm sạch khe gạch, bánh xe hiệu quả hơn đầu thẳng.",
    media: [mediaImg("prod-acc-voi-xoay", 0, "Đầu phun xoay 360")],
  },
];

export const seedLeads: Lead[] = [
  {
    id: "lead-001",
    productId: "prod-dekton-dk-1800",
    name: "Nguyễn Văn An",
    phone: "0901234567",
    note: "Muốn tư vấn máy rửa xe máy + sân nhà",
    createdAt: "2026-07-18T09:30:00.000Z",
  },
  {
    id: "lead-002",
    productId: "prod-karcher-k5",
    name: "Trần Thị Bình",
    phone: "0918765432",
    note: "Hỏi bảo hành và giao hàng HCM",
    createdAt: "2026-07-19T14:15:00.000Z",
  },
];
